# Generated by Django 2.2 on 2019-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(max_length=200)),
                ('index_content', models.TextField()),
                ('index_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
